import axios from 'axios';
window.axios = axios;
window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
const csrf_token = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
window.axios.defaults.headers.common['X-CSRF-TOKEN'] = csrf_token;
import Swal from 'sweetalert2';
window.Swal = Swal;
import 'sweetalert2/src/sweetalert2.scss';
import "@lottiefiles/lottie-player";
import '@popperjs/core/dist/umd/popper.min.js';
import 'bootstrap/dist/js/bootstrap.min.js';
import 'adminlte4/dist/js/adminlte.min.js';
import 'jquery/dist/jquery.min.js';
import 'select2/dist/js/select2.full.min.js';
import 'datatables.net/js/jquery.dataTables.min.js';
